// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleAppsScriptType
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Drive add-on manifest.
public struct DriveAddOnManifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If present, this overrides the configuration from
  /// `addOns.common.homepageTrigger`.
  public var homepageTrigger: GoogleAppsScriptType.HomepageExtensionPoint? = nil

  /// Corresponds to behvior that should execute when items are selected
  /// in relevant Drive view (e.g. the My Drive Doclist).
  public var onItemsSelectedTrigger: DriveExtensionPoint? = nil

  /// Initialize a new instance of `DriveAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DriveAddOnManifest().with { $0.homepageTrigger = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.drive.DriveAddOnManifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
